### ISSUE TITLE
Spike extractor 1

### ISSUE THREAD

**Issue by StoneyJackson** [foss2serve/corral-dev#2]
Learning Objectives:
- Primary: Make requests to GitHub API
- Primary: Receive JSON data from GitHub API
- Secondary: Authenticate to GitHub API

Task: Implement a program/function/script that exhibits the following behavior
- Input: URL to git repository
- Output: JSON data for the repository as given by GitHub API

**Comment by tonytran** [comment]
working/json_extractor.py
